# Generated by Django 5.0.3 on 2025-03-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
