# Generated by Django 5.0.3 on 2025-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0005_remove_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='oaauth.role'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
