# Generated by Django 5.0.3 on 2025-03-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0006_user_roles_delete_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
