# Generated by Django 5.0.3 on 2025-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oaauth", "0007_rename_roles_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
