# Generated by Django 5.0.3 on 2025-03-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absenttype',
            name='create_time',
        ),
        migrations.AlterModelTable(
            name='absent',
            table='absent',
        ),
        migrations.AlterModelTable(
            name='absenttype',
            table='absent_type',
        ),
    ]
