# Generated by Django 5.0.3 on 2025-03-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0002_remove_absenttype_create_time_alter_absent_table_and_more'),
        ('oaauth', '0007_rename_roles_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absent',
            name='responder',
        ),
        migrations.AddField(
            model_name='absent',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_absents', related_query_name='sub_absents', to='oaauth.department'),
        ),
    ]
