# Generated by Django 5.0.3 on 2025-03-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inform',
            table='inform',
        ),
        migrations.AlterModelTable(
            name='informread',
            table='inform_read',
        ),
    ]
